#!/bin/bash

mysql -u$MIGRATIONS_WORKS_TEST_DB_USER -p$MIGRATIONS_WORKS_TEST_DB_PASSWORD -h$MIGRATIONS_WORKS_TEST_DB_HOST <<EOF
CREATE DATABASE IF NOT EXISTS migrations_works_tests;

USE migrations_works_tests;

CREATE TABLE IF NOT EXISTS migrations_works_tests (
    id INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    username VARCHAR(255) NOT NULL,
    password VARCHAR(255) NOT NULL,
    email VARCHAR(255) NOT NULL,
    profile VARCHAR(255) NOT NULL
) ENGINE=InnoDb CHARSET=utf8mb3 COLLATE=utf8mb3_general_ci;

EOF
